#pragma config(Sensor, S1,     ,               sensorEV3_Color)
#pragma config(Sensor, S2,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void Turn_right(int power,int overR)
{
while(getMotorEncoder(motorB)<=60)
{setMotorSpeed(motorB,power);
setMotorSpeed(motorC,-power);
}
while(getColorReflected(S2)>=40)
{
setMotorSpeed(motorB,power);
setMotorSpeed(motorC,-power);
}
resetMotorEncoder(motorB);
while(getMotorEncoder(motorB)<=overR)
{
setMotorSpeed(motorB,power);
setMotorSpeed(motorC,-power);
}
setMotorSpeed(motorB,0);
setMotorSpeed(motorC,0);
delay(1000);
}
void Turn_left(int overR,int power)
{
while(getMotorEncoder(motorC)<=60)
{setMotorSpeed(motorB,-power);
setMotorSpeed(motorC,power);
}
while(getColorReflected(S2)>=40)
{
setMotorSpeed(motorB,-power);
setMotorSpeed(motorC,power);
}
resetMotorEncoder(motorB);
while(getMotorEncoder(motorC)<=overR)
{
setMotorSpeed(motorB,-power);
setMotorSpeed(motorC,power);
}
setMotorSpeed(motorB,0);
setMotorSpeed(motorC,0);
delay(1000);
}
task main()
{
Turn_left(30,40);
}
