#pragma config(Sensor, S1,     ,               sensorEV3_Color)
#pragma config(Sensor, S2,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void line_tracing(float kp,float kd, float ki,int bp,unsigned int thr,int degree)
{
float old;
float err;
float integral;
float PID;
bool flag;
flag=true;
while(flag||getMotorEncoder(motorB)<=degree)
{
old=err;
integral=integral*0.1+err;
err=getColorReflected(S1)-getColorReflected(S2);
PID=(err*kp+(err-old)*kd+integral*ki);
setMotorSpeed(motorB, bp+PID);
setMotorSpeed(motorC, bp-PID);
if(flag&&getColorReflected(S1)+getColorReflected(S2)<=thr)
{
resetMotorEncoder(motorB);
flag=false;
}
}
}
task main()
{
line_tracing(0.2,0.2,0,15,70,140);
setMotorSpeed(motorB,0);
setMotorSpeed(motorC,0);
}
